export const getRandomQuote = (quotes) => {
  const randomIndex = Math.floor(Math.random() * quotes.length -1);
  return quotes[randomIndex];
}

export const famousQuotes = [
  "be yourself everyone else is already taken",
  "the only way to do great work is to love what you do",
  "to be or not to be that is the question",
  "you miss 100 of the shots you dont take",
  "the journey of a thousand miles begins with one step",
  "i think therefore i am",
  "in the end we will remember not the words of our enemies but the silence of our friends",
  "life is what happens when youre busy making other plans",
  "be the change that you wish to see in the world",
  "it does not do to dwell on dreams and forget to live",
  "the unexamined life is not worth living",
  "to love and be loved is to feel the sun from both sides",
  "you only live once but if you do it right once is enough",
  "success is not final failure is not fatal",
  "what we think we become",
  "it always seems impossible until its done",
  "the best way to predict the future is to create it",
  "life is really simple but we insist on making it complicated",
  "happiness depends upon ourselves",
  "we are what we repeatedly do excellence then is not an act but a habit",
  "the only limit to our realization of tomorrow is our doubts of today",
  "act as if what you do makes a difference it does",
  "believe you can and youre halfway there",
  "you do not find the happy life you make it",
  "in three words i can sum up everything ive learned about life it goes on",
  "the purpose of our lives is to be happy",
  "be not afraid of life believe that life is worth living",
  "do not go gentle into that good night",
  "you are never too old to set another goal",
  "in the middle of difficulty lies opportunity",
  "success usually comes to those who are too busy to be looking for it",
  "the best revenge is massive success",
  "dream as if youll live forever live as if youll die today",
  "everything has beauty but not everyone can see it",
  "life isnt about finding yourself life is about creating yourself",
  "the only impossible journey is the one you never begin",
  "do what you can with what you have where you are",
  "you have within you right now everything you need",
  "the only thing we have to fear is fear itself",
  "if you tell the truth you dont have to remember anything",
  "the best way out is always through",
  "life is short and it is up to you to make it sweet",
  "the only source of knowledge is experience",
  "dont watch the clock do what it does keep going",
  "life is not measured by the number of breaths we take",
  "to love and be loved is to feel the sun from both sides",
  "what we achieve inwardly will change outer reality",
  "you must be the change you wish to see in the world",
  "the best way to find yourself is to lose yourself in the service of others",
  "to live is the rarest thing in the world most people exist",
  "the greatest wealth is to live content with little",
  "everything youve ever wanted is on the other side of fear",
  "success is stumbling from failure to failure with no loss of enthusiasm",
  "the way to get started is to quit talking and begin doing",
  "you are never too old to set another goal or to dream a new dream",
  "your time is limited so dont waste it living someone elses life",
  "the best time to plant a tree was 20 years ago the second best time is now",
  "you dont have to be great to start but you have to start to be great",
  "the only person you are destined to become is the person you decide to be",
  "your life does not get better by chance it gets better by change",
  "the harder i work the luckier i get",
  "success is going from failure to failure without losing your enthusiasm",
  "you cant use up creativity the more you use the more you have",
  "opportunities dont happen you create them",
  "the future belongs to those who believe in the beauty of their dreams",
  "you are not your resume you are your work",
  "the only limit to our realization of tomorrow is our doubts of today",
  "whatever you are be a good one",
  "do not wait to strike till the iron is hot but make it hot by striking",
  "what you get by achieving your goals is not as important as what you become by achieving your goals",
  "the only way to achieve the impossible is to believe it is possible",
  "life isnt about waiting for the storm to pass its about learning how to dance in the rain",
  "the best preparation for tomorrow is doing your best today",
  "if you want to lift yourself up lift up someone else",
  "you dont have to be perfect to be amazing",
  "the only real mistake is the one from which we learn nothing",
  "the secret of getting ahead is getting started",
  "do what you can with what you have where you are",
  "our greatest glory is not in never falling but in rising every time we fall",
  "it is never too late to be what you might have been",
  "life is 10 what happens to us and 90 how we react to it",
  "the only thing standing between you and your goal is the story you keep telling yourself",
  "the best dreams happen when youre awake",
  "its not whether you get knocked down its whether you get up",
  "the more i want to get something done the less i call it work",
  "the purpose of life is not to be happy it is to be useful",
  "if you want to live a happy life tie it to a goal not to people or things",
  "you dont have to be great to start but you have to start to be great",
  "the only way to do great work is to love what you do",
  "success is not in what you have but who you are",
  "dont let what you cannot do interfere with what you can do",
  "the difference between a successful person and others is not a lack of strength not a lack of knowledge but rather a lack in will",
  "you are never too old to set another goal or to dream a new dream",
  "dont be pushed around by the fears in your mind be led by the dreams in your heart",
  "be not afraid of life believe that life is worth living",
  "you only live once but if you do it right once is enough"
]